spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:C:/data/estado_db_rony
    username: sa
    password: 
  h2:
   console:
      enabled: true
      path: /h2
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    generate-ddl: true
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
server:
  port: 8090 #set your port