--liquibase formatted sql

--changeset ronybrand:1
--preConditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'estado'
--comment: cria a tabela estado - espelha o schema que o Hibernate ddl-auto:update
--comment: gerava, pra nao quebrar bancos ja existentes (ver ADR 0014). A precondition
--comment: detecta se a tabela ja existe (caso da producao atual): se sim, o Liquibase
--comment: so marca este changeset como aplicado, sem tentar recriar a tabela.
CREATE TABLE estado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    sigla VARCHAR(2) NOT NULL,
    ts_data_hora_cadastro TIMESTAMP NOT NULL,
    ts_data_hora_ultima_atualizacao TIMESTAMP,
    CONSTRAINT uniqueNomeConstraint UNIQUE (nome),
    CONSTRAINT uniqueSiglaConstraint UNIQUE (sigla)
);
--rollback DROP TABLE estado;
